services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ['CMD', 'ollama', 'list']
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  app:
    build: .
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - STREAMLIT_PORT=8501
    volumes:
      - chroma_db:/app/chroma_db
    ports:
      - '8501:8501'
    command: >
      sh -c "
        echo 'Attente du démarrage complet d Ollama...' &&
        sleep 10 &&
        echo 'Téléchargement du modèle all-minilm:latest...' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"all-minilm:latest\"}' &&
        echo 'Téléchargement du modèle phi3:3.8b...' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"phi3:3.8b\"}' &&
        echo 'Lancement de l application...' &&
        uv run streamlit run app/app.py --server.port=8501 --server.address=0.0.0.0
      "

volumes:
  chroma_db:
  ollama:
